<p><a href="<?php echo $this->url(
    array(
        'controller' => 'karyawan2',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>
 
Guestbook Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    	<dt><?php echo $this->escape($entry->id) ?></dt>
    	<dt><?php echo $this->escape($entry->nama) ?></dt>
    <dt><?php echo $this->escape($entry->email) ?></dt>
    <dd><?php echo $this->escape($entry->tgllahir) ?></dd>
    <?php endforeach ?>
</dl>