<!-- application/views/scripts/guestbook/index.phtml -->
 
<p><a href="<?php echo $this->url(
    array(
        'controller' => 'karyawan',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Tambah Karyawan</a></p>
 
Daftar Nama Karyawan: <br />


<table class="table table-striped table-hover table-bordered"><th>Nama</th><th>Email</th>
  <?php  foreach($this->entries as $entry): ?>
  
        <tr>
        <td><?php echo $this->escape($entry->id) ?></td>
            <td><?php echo $this->escape($entry->nama) ?></td>
            <td><?php echo $this->escape($entry->email) ?></td>
        </tr>
  <?php endforeach;?>
</table>